/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TAMPILAN;

import CONTROL.c_buku;
import CONTROL.c_karyawan;
import KONEKSI.koneksi;
import MODEL.buku;
import MODEL.karyawan;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
//import library

public class daftarbuku extends javax.swing.JFrame {

  
    public daftarbuku() {
        initComponents();
           Dimension layar=Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
//menset tampilan agar ditengah layar
        this.setLocation(x, y);
        refresh();//memanggil refresh
    }
     buku buk = new buku();
    c_buku ctrl = new c_buku(koneksi.getKoneksi());
    List<buku> list = new ArrayList();//membuat list
    public void refresh() {
        list = ctrl.getbuku();//memanggil getbuku di CONTROL
        String[][] data = new String[list.size()][6];
        int i = 0;
        for (buku li : list) {
            data[i][0] = String.valueOf(li.getIdbuku());
            data[i][1] = String.valueOf(li.getJudul());
            data[i][2] = String.valueOf(li.getJumlah());
            data[i][3] = String.valueOf(li.getPenulis());
            data[i][4] = String.valueOf(li.getPenerbit());
            data[i][5] = String.valueOf(li.getTahunterbit());
           
  

            i++;
        }
        tabelbuku.setModel(new DefaultTableModel(data, new String[]{"idbuku", "judul","Jumlah","penulis", 
            "Penerbit", "Tahunterbit"
           }));//mencetak data ke tabel

    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        penulis = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idbuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(834, 542));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 542));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 542));
        jPanel1.setPreferredSize(new java.awt.Dimension(834, 542));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tabelbuku.setForeground(new java.awt.Color(255, 255, 255));
        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Buku", "Judul", "Jumlah", "Penulis", "penerbit", "tahunterbit"
            }
        ));
        tabelbuku.setColumnSelectionAllowed(false);
        tabelbuku.setGridColor(new java.awt.Color(255, 255, 255));
        tabelbuku.setSelectionBackground(new java.awt.Color(233, 78, 49));
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelbuku);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 660, 140));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/tambah1.png"))); // NOI18N
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahMouseExited(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 140, 30));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/simpan1.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanMouseExited(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 140, 30));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/hapus1.png"))); // NOI18N
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusMouseExited(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 140, 30));

        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        jPanel1.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tahun Terbit:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        penulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penulisActionPerformed(evt);
            }
        });
        jPanel1.add(penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 160, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Penulis:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        idbuku.setEditable(false);
        idbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbukuActionPerformed(evt);
            }
        });
        jPanel1.add(idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 160, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Id buku:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 210, -1));

        penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitActionPerformed(evt);
            }
        });
        jPanel1.add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Penerbit:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Judul:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumActionPerformed(evt);
            }
        });
        jPanel1.add(jum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 210, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/icons8-back-arrow-48.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/icons8-close-window-48.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Register Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 370, 70));

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbukuActionPerformed

    private void jumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumActionPerformed

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerbitActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    private void penulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penulisActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();//menghilangkan menu ini
        menuadmin a=new menuadmin();//membuat objek a
        a.setVisible(true);//memanggil objek lalu menampilkan menuadmin
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);//keluar
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
      ImageIcon A=new ImageIcon(getClass().getResource("images/back1.png"));
      jLabel8.setIcon(A);//mengganti icon dengan gambar
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
       ImageIcon A=new ImageIcon(getClass().getResource("images/icons8-back-arrow-48.png"));
      jLabel8.setIcon(A);//mengganti icon dengan gambar
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
   ImageIcon A=new ImageIcon(getClass().getResource("images/close1_1.png"));
      jLabel9.setIcon(A);//mengganti icon dengan gambar
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
    ImageIcon A=new ImageIcon(getClass().getResource("images/icons8-close-window-48.png"));
      jLabel9.setIcon(A);//mengganti icon dengan gambar
    }//GEN-LAST:event_jLabel9MouseExited

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        buk.setJudul(judul.getText().toString());
        buk.setPenulis(penulis.getText().toString());
        buk.setPenerbit(penerbit.getText().toString());
        buk.setTahunterbit(tahun.getText().toString());
        buk.setJumlah(Integer.parseInt(jum.getText().toString()));
       //menset sesuai yang diambil di txtfield
        
        boolean tambah = ctrl.inputbuku(buk);//memanggil inputbuku dicontrol
        
        if (tambah == true) {
            JOptionPane.showMessageDialog(null, "Berhasil Tambah data", "Info", JOptionPane.INFORMATION_MESSAGE);
            refresh();//memanggil refresh,menampilkan message diatas
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
   int kode = Integer.parseInt(idbuku.getText().toString());//mengubah string ke integer
   int juml = Integer.parseInt(jum.getText().toString());//mengubah string ke integer
        String jud = judul.getText().toString();
        String pen =penulis.getText().toString();
        String penet = penerbit.getText().toString();
        String tahunn = tahun.getText().toString();
       //mengambil data dari txtfield dan memasukan dalam suatu variabel
        try {
            int jwb = JOptionPane.showConfirmDialog(null, "Apakah anda Yakin Edit data buku ini ?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (jwb == JOptionPane.YES_OPTION) {//jika ya update dijalankan
                String update = ctrl.Updatebuku(kode,jud,pen,penet,tahunn,juml);//mengupdate tabel dengan variabel yang tadi
                refresh();//memanggil refresh
                if (update.equals("berhasil update")) {
                    JOptionPane.showMessageDialog(null, "Berhasil Edit Buku", "Info", JOptionPane.INFORMATION_MESSAGE);//menampilkan message
                    refresh();//memanggil refresh
                }
            } else {
                return;
            }

        } catch (Exception e) {
        }    
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {//menghapus data sesuai dengan idbuku
            int jwb = JOptionPane.showConfirmDialog(null, "Apakah anda Yakin Menghapus buku ini ?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (jwb == JOptionPane.YES_OPTION) {//jika jwb =yes maka data yang memiliki idbuku sekian akan dihapus
                String hps = ctrl.hapus(idbuku.getText().toString());
                if (hps.equals("berhasil hapus")) {
                    JOptionPane.showMessageDialog(null, "Berhasil Menghapus Buku", "Info", JOptionPane.INFORMATION_MESSAGE);
                    refresh();//berhasil dhapus lalu tabel direfresh
                }
            }else{
                return;
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseEntered
  ImageIcon A=new ImageIcon(getClass().getResource("images/hapus2.png"));
      hapus.setIcon(A); //mengganti icon
    }//GEN-LAST:event_hapusMouseEntered

    private void hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseExited
       ImageIcon A=new ImageIcon(getClass().getResource("images/hapus1.png"));
      hapus.setIcon(A);//mengganti icon
    }//GEN-LAST:event_hapusMouseExited

    private void simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseEntered
    ImageIcon A=new ImageIcon(getClass().getResource("images/simpan2.png"));
      simpan.setIcon(A);//mengganti icon
    }//GEN-LAST:event_simpanMouseEntered

    private void simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseExited
      ImageIcon A=new ImageIcon(getClass().getResource("images/simpan1.png"));
      simpan.setIcon(A);//mengganti icon
    }//GEN-LAST:event_simpanMouseExited

    private void tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseExited
 ImageIcon A=new ImageIcon(getClass().getResource("images/tambah1.png"));
      tambah.setIcon(A);//mengganti icon
    }//GEN-LAST:event_tambahMouseExited

    private void tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseEntered
  ImageIcon A=new ImageIcon(getClass().getResource("images/tambah2.png"));
      tambah.setIcon(A);//mengganti icon
    }//GEN-LAST:event_tambahMouseEntered

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
    idbuku.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 0).toString());
   judul.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 1).toString());
   jum.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 2).toString());
   penulis.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 3).toString());
   penerbit.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 4).toString());
   tahun.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 5).toString());
  //menset txtfield ketika tabel dipencet salah satu barisnya
    }//GEN-LAST:event_tabelbukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarbuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jum;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField penulis;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JTextField tahun;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
