/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TAMPILAN;

import CONTROL.c_karyawan;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import CONTROL.c_member;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import KONEKSI.koneksi;
import MODEL.karyawan;

import java.sql.Connection;


/**
 *
 * @author x.x
 */
public class daftarkaryawan extends javax.swing.JFrame {

    /**
     * Creates new form daftarpeminjam
     */
    public daftarkaryawan() {
        initComponents();
         Dimension layar=Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        refresh();
    }
  karyawan kar = new karyawan();
    c_karyawan ctrl = new c_karyawan(koneksi.getKoneksi());
    List<karyawan> list = new ArrayList();
    public void refresh() {
        list = ctrl.getkaryawan();
        String[][] data = new String[list.size()][8];
        int i = 0;
        for (karyawan li : list) {
            data[i][0] = String.valueOf(li.getIdkaryawan());
            data[i][1] = String.valueOf(li.getUsername());
            data[i][2] = String.valueOf(li.getPassword());
            data[i][3] = String.valueOf(li.getNama());
            data[i][4] = String.valueOf(li.getTgllahir());
            data[i][5] = String.valueOf(li.getAlamat());
            data[i][6] = String.valueOf(li.getNohp());
            data[i][7] = String.valueOf(li.getJeniskel());
  

            i++;
        }
        tabelkaryawan.setModel(new DefaultTableModel(data, new String[]{"idkaryawan", "username","password","nama", 
            "tgllahir", "alamat",
            "nohp","jeniskel"}));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idkaryawan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        back = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        perem = new javax.swing.JRadioButton();
        tgl = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        namaa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        nohpp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        setuju = new javax.swing.JCheckBox();
        simpan = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelkaryawan = new javax.swing.JTable();
        jeniskel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alamatt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(834, 540));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/tambah1.png"))); // NOI18N
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tambahMousePressed(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 140, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("DD/MM/YY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        idkaryawan.setEditable(false);
        getContentPane().add(idkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Idkaryawan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");
        getContentPane().add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/backbut.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/close1.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        buttonGroup1.add(perem);
        perem.setText("Perempuan");
        getContentPane().add(perem, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 200, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 150, -1));
        getContentPane().add(namaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 200, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Masukkan ulang password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/hapus1.png"))); // NOI18N
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusMouseExited(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 140, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nama Lengkap:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Jenis kelamin:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, -1));
        getContentPane().add(nohpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("No Hp:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        setuju.setText("Setuju");
        setuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujuActionPerformed(evt);
            }
        });
        getContentPane().add(setuju, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/simpan1.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanMouseExited(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 140, 20));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 150, -1));

        tabelkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idkaryawan", "username", "password", "nama", "tgllahir", "alamat", "nohp", "jeniskel"
            }
        ));
        tabelkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkaryawanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelkaryawan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 440, 90));

        jeniskel.setEditable(false);
        getContentPane().add(jeniskel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 40, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Alamat:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));
        getContentPane().add(alamatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/pagekarreg.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
      System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
      ImageIcon A=new ImageIcon(getClass().getResource("images/backbut2.png"));
      back.setIcon(A);
    }//GEN-LAST:event_backMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
   ImageIcon A=new ImageIcon(getClass().getResource("images/close1.png"));
      close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       ImageIcon A=new ImageIcon(getClass().getResource("images/close2.png"));
      close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon A=new ImageIcon(getClass().getResource("images/backbut.png"));
      back.setIcon(A);
    }//GEN-LAST:event_backMouseExited

    private void tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseEntered
ImageIcon A=new ImageIcon(getClass().getResource("images/tambah2.png"));
      tambah.setIcon(A);
    }//GEN-LAST:event_tambahMouseEntered

    private void tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseExited
       ImageIcon A=new ImageIcon(getClass().getResource("images/tambah1.png"));
      tambah.setIcon(A);
    }//GEN-LAST:event_tambahMouseExited

    private void hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseEntered
      ImageIcon A=new ImageIcon(getClass().getResource("images/hapus2.png"));
      hapus.setIcon(A);
    }//GEN-LAST:event_hapusMouseEntered

    private void hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseExited
  ImageIcon A=new ImageIcon(getClass().getResource("images/hapus1.png"));
      hapus.setIcon(A);
    }//GEN-LAST:event_hapusMouseExited

    private void tambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMousePressed
  
    }//GEN-LAST:event_tambahMousePressed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
 
    }//GEN-LAST:event_tambahMouseClicked

    private void tabelmembidkaryawancked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmemberMouseClicked
      
    }//GEN-LAST:event_tabelmemberMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        
        try {  
            int jwb = JOptionPane.showConfirmDialog(null, "Apakah anda Yakin Menghapus Karyawan ini ?", "Peringatan", JOptionPane.YES_NO_OPTION);
                    if (jwb == JOptionPane.YES_OPTION) {
                String hps = ctrl.hapus(idkaryawan.getText().toString());
                idkaryawan.setText("");
        user.setText("");
        pass1.setText("");
        pass2.setText("");
        tgl.setText("");
        alamatt.setText("");
        nohpp.setText("");
        namaa.setText("");
        jeniskel.setText("");
                if (hps.equals("berhasil hapus")) {
                    JOptionPane.showMessageDialog(null, "Berhasil Menghapus Karyawan", "Info", JOptionPane.INFORMATION_MESSAGE);
                    refresh();
                }
            }else{
                return;
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
       String username=user.getText().toString();
        String pw1=new String(pass1.getPassword());
        String pw2= new String(pass2.getPassword());
        String nama = namaa.getText().toString();
        String tgll = tgl.getText().toString();
        String alamat = alamatt.getText().toString();
         String jk="";
         if (laki.isSelected()) {
            jk="L";
        }else if (perem.isSelected()) {
            jk="P";
        }
        String nohp = nohpp.getText().toString();
       boolean cek=false;
        if (setuju.isSelected()) {
            cek=true;
        }
        if(!cek){
            JOptionPane.showMessageDialog(null, "harus setuju");
        }
        else if (username.isEmpty()||pw1.isEmpty()||pw2.isEmpty()||nama.isEmpty()||tgll.isEmpty()||alamat.isEmpty()||nohp.isEmpty()||jk.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }else if (!pw1.equals(pw2)) {
            JOptionPane.showMessageDialog(null, "password tidak sama!");
        }
    
        else{
       
       kar.setUsername(username);
     kar.setPassword(pw2);
       kar.setNama(nama);
        kar.setTgllahir(tgll);
        kar.setAlamat(alamat);
        kar.setNohp(nohp);
        kar.setJeniskel(jk);
       
        
        boolean tambah = ctrl.inputkaryawan(kar);
        
        if (tambah == true) {
            JOptionPane.showMessageDialog(null, "Berhasil Tambah data", "Info", JOptionPane.INFORMATION_MESSAGE);
            refresh();
        }}
    }//GEN-LAST:event_tambahActionPerformed

    private void tabelkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkaryawanMouseClicked
        idkaryawan.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 0).toString());
       user.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(),1).toString());
       pass1.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(),2).toString());
       pass2.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(),2).toString());
       namaa.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 3).toString());
       tgl.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 4).toString());
       alamatt.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 5).toString());
       nohpp.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 6).toString());
       jeniskel.setText(tabelkaryawan.getValueAt(tabelkaryawan.getSelectedRow(), 7).toString());
        
    }//GEN-LAST:event_tabelkaryawanMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        int kode = Integer.parseInt(idkaryawan.getText().toString());
        String username=user.getText().toString();
        String pw1=new String (pass1.getPassword());
        String pw2=new String(pass2.getPassword());
        String nama = namaa.getText().toString();
        String tgll = tgl.getText().toString();
        String alamat = alamatt.getText().toString();
        String nohp = nohpp.getText().toString();
        String jeniskelamin="";
        if (laki.isSelected()) {
            jeniskelamin="L";
        }else if (perem.isSelected()) {
            jeniskelamin="P";
        }
        if (username.isEmpty()||pw1.isEmpty()||pw2.isEmpty()||nama.isEmpty()||tgll.isEmpty()||alamat.isEmpty()||nohp.isEmpty()||jeniskelamin.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }
        else if (!pw1.equals(pw2)) {
            JOptionPane.showMessageDialog(null, "password tidak sama!!");
        }else{
        
       
        try {
            int jwb = JOptionPane.showConfirmDialog(null, "Apakah anda Yakin Edit data karyawan ini ?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (jwb == JOptionPane.YES_OPTION) {
                String update = ctrl.Updatekaryawan(username, pw1,kode,nama, tgll,alamat,nohp,jeniskelamin);
                refresh();
                if (update.equals("berhasil update")) {
                    JOptionPane.showMessageDialog(null, "Berhasil Edit data karyawan", "Info", JOptionPane.INFORMATION_MESSAGE);
                    refresh();
                }
            } else {
                return;
            }

        } catch (Exception e) {
        }}
    }//GEN-LAST:event_simpanActionPerformed

    private void simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseEntered
        ImageIcon A=new ImageIcon(getClass().getResource("images/simpan2.png"));
      simpan.setIcon(A);
    }//GEN-LAST:event_simpanMouseEntered

    private void simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseExited
         ImageIcon A=new ImageIcon(getClass().getResource("images/simpan1.png"));
      simpan.setIcon(A);
    }//GEN-LAST:event_simpanMouseExited

    private void setujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setujuActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         idkaryawan.setText("");
        user.setText("");
        pass1.setText("");
        pass2.setText("");
        tgl.setText("");
        alamatt.setText("");
        nohpp.setText("");
        namaa.setText("");
        jeniskel.setText("");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       this.dispose();
       menuadmin a=new menuadmin();
       a.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatt;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idkaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jeniskel;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField namaa;
    private javax.swing.JTextField nohpp;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JRadioButton perem;
    private javax.swing.JCheckBox setuju;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelkaryawan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tgl;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
