 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TAMPILAN;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author x.x
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public signup() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        Dimension layar=Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tahunn = new javax.swing.JTextField();
        close = new javax.swing.JLabel();
        namaa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bulann = new javax.swing.JComboBox<>();
        pass2 = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JPasswordField();
        usernamee = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tanggall = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alamatt = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        kotaa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        syaratt = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(834, 542));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tahunn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 80, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/close1.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));
        getContentPane().add(namaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 580, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Username:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, -1));

        bulann.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Okt", "Nov", "Dec" }));
        getContentPane().add(bulann, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 80, -1));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 280, -1));
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 280, -1));
        getContentPane().add(usernamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 580, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Syarat dan Ketentuan kami");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 260, -1));

        tanggall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(tanggall, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Masukkan ulang password");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 170, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, -1));
        getContentPane().add(alamatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 580, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setText("Perempuan");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));
        getContentPane().add(kotaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 350, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Dengan ini anda menyetujui");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 260, -1));

        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/signup1.png"))); // NOI18N
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 310, 60));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Jenis Kelamin");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, -1));

        syaratt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(syaratt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setText("Laki-Laki");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Lahir");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Kota");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nama Lengkap");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/backbut.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/images/signuppage.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
      
        String nama=namaa.getText();
       String kota=kotaa.getText();
       String alamat=alamatt.getText();
       String tanggal= tanggall.getSelectedItem().toString();
       String bulan= bulann.getSelectedItem().toString();
       String tahun=tahunn.getText();
       String username=usernamee.getText();
       String tanggallahir=tanggal+"/"+bulan+"/"+tahun;
       
       String jeniskel="";
       if(male.isSelected()){
           jeniskel="Laki-Laki";
       } else if(female.isSelected()){
           jeniskel="Perempuan";
       }
       String pw1= new String(pass1.getPassword());
       String pw2= new String(pass2.getPassword());
       boolean cek=false;
        if (syaratt.isSelected()) {
            cek=true;
        }
        if (nama.isEmpty()||kota.isEmpty()||tanggal.isEmpty()||bulan.isEmpty()||
            tahun.isEmpty()||alamat.isEmpty()||username.isEmpty()||pw1.isEmpty()||
            pw2.isEmpty()||jeniskel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong!!");
        }else if (!pw1.equals(pw2)) {
              JOptionPane.showMessageDialog(null, "Password Tidak Sama!!");
        }else if(!cek){
              JOptionPane.showMessageDialog(null, "Harus menyetujui!!");
        }else{
            int dialogButton=JOptionPane.YES_NO_OPTION;
            String dialog="Nama Lengkap:"+nama+"\n"
                    +"Username:"+username+"\n"
                    +"Tempat Tanggal Lahir:"+kota+","+tanggallahir+"\n"
                    +"Jenis Kelamin:"+jeniskel+"\n"
                    +"Apakah sudah benar?";
            int dialogResult=JOptionPane.showConfirmDialog(null, dialog, "konfirmasi", dialogButton);
            if (dialogResult==JOptionPane.YES_OPTION) {
                
                JOptionPane.showMessageDialog(null, "Input Berhasil");
            }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
   this.dispose();
awal a= new awal();
a.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon A=new ImageIcon(getClass().getResource("images/backbut2.png"));
      back.setIcon(A);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
      ImageIcon A=new ImageIcon(getClass().getResource("images/backbut.png"));
      back.setIcon(A);
    }//GEN-LAST:event_backMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
     ImageIcon A=new ImageIcon(getClass().getResource("images/close2.png"));
      close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
         ImageIcon A=new ImageIcon(getClass().getResource("images/close1.png"));
      close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      JOptionPane.showMessageDialog(null,"Terms and conditions\n" +
"\n" +
"These terms and conditions (\"Terms\", \"Agreement\")"
             + "are an agreement between Desktop Application Developer\n (\"Desktop Application Developer\", \"us\", \"we\""
             + " or \"our\") and you (\"User\", \"you\" or \"your\"). This Agreement sets forth\n the general terms and conditions of your use of the db desktop application and any of its products or services\n (collectively, \"Mobile Application\" or \"Services\").");
     
    }//GEN-LAST:event_jLabel12MouseClicked

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
     ImageIcon A=new ImageIcon(getClass().getResource("images/signupbut2.png"));
      signup.setIcon(A);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
      ImageIcon A=new ImageIcon(getClass().getResource("images/signup1_1.png"));
      signup.setIcon(A);
    }//GEN-LAST:event_signupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatt;
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> bulann;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kotaa;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField namaa;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JButton signup;
    private javax.swing.JRadioButton syaratt;
    private javax.swing.JTextField tahunn;
    private javax.swing.JComboBox<String> tanggall;
    private javax.swing.JTextField usernamee;
    // End of variables declaration//GEN-END:variables
}
